# Summary:
# Upon release, automatically update the MAJOR tag to make it point to the latest version of any minor/patch release, for easy use by the consumers.
# Also updates the "latest" tag automatically (auto-created), which is meant to be used for development/testing only, not for production.
# This way, consumers can use @v1 and the @v1 is a tag that is automatically updated when you release a new v1 minor/patch version.

name: 'GitHub Action tag releases'
on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v2.0.1 # See https://github.com/Actions-R-Us/actions-tagger
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        with:
          publish_latest_tag: true
